name = "ns"
main = "src/index.js"
compatibility_date = "2024-01-01"

[triggers]
crons = ["0 0 * * *", "0 * * * *", "0 0 * * 0"]

[[r2_buckets]]
binding = "NS_DATA"
bucket_name = "ns-data"

[[d1_databases]]
binding = "DB"
database_name = "ns-db"
database_id = "YOUR_D1_DATABASE_ID"

[[kv_namespaces]]
binding = "CACHE"
id = "YOUR_KV_NAMESPACE_ID"

[vars]
NASA_API_KEY = "ILeecsesMNeEs1LBJRa8G2R5RYKdp0I50d4nbyOo"
