name = "ns"
main = "src/index.js"
compatibility_date = "2024-01-01"

[triggers]
crons = ["0 0 * * *", "0 * * * *", "0 0 * * 7"]

[[r2_buckets]]
binding = "NS_DATA"
bucket_name = "ns-data"

[[d1_databases]]
binding = "DB"
database_name = "ns-db"
database_id = "b840a4de-1968-4fdd-8926-f30646f0d18c"

[[kv_namespaces]]
binding = "CACHE"
id = "f117a5c5ed774d51b44981e3776e7580"

[vars]
NASA_API_KEY = "ILeecsesMNeEs1LBJRa8G2R5RYKdp0I50d4nbyOo"
